[package]
name = "soksak-tauriv2"
version = "0.0.1"
edition = "2021"
description = "soksak layout running in Tauri v2"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
soksak-host-tauriv2 = { path = "../../packages/host/tauriv2" }
tauri = { version = "2", features = ["unstable"] }
